/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;
/*!40101 SET SQL_MODE='NO_AUTO_VALUE_ON_ZERO,ONLY_FULL_GROUP_BY,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'*/;
/*!40103 SET TIME_ZONE='+00:00' */;
CREATE TABLE `users` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `first_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `last_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `role` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'user',
  `gender` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `age` date DEFAULT NULL,
  `country` bigint unsigned DEFAULT NULL,
  `city` bigint unsigned DEFAULT NULL,
  `language` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `profile_pic` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `phone` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `zip_code` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `postal_code` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `Speaking_Languages` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address` text COLLATE utf8mb4_unicode_ci,
  `fees` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `service_type` enum('onsite','remote','both') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'onsite',
  `speciality` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `specialties` bigint unsigned DEFAULT NULL,
  `sxpertise` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `Access_info` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `healthcare_professional_info` text COLLATE utf8mb4_unicode_ci,
  `about_me` text COLLATE utf8mb4_unicode_ci,
  `payment_method` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `latitude` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `longitude` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `otp` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_online` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '1',
  `is_active` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '0',
  `token` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '0',
  `status` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '0',
  `title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `house_number` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hin_email` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fax_phone_number` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fax_number` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reviwes` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `patient_status` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `boost_end_at` timestamp NULL DEFAULT NULL,
  `is_boosted` tinyint(1) NOT NULL DEFAULT '0',
  `web_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `institute_id` bigint unsigned DEFAULT NULL,
  `zefix_ide` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `extension_code` bigint DEFAULT NULL,
  `wallet` decimal(10,2) DEFAULT NULL,
  `sms_reminder` tinyint(1) DEFAULT NULL,
  `sms_confirmation` tinyint(1) DEFAULT NULL,
  `referral_code` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_extension_code_unique` (`extension_code`)
) ENGINE=InnoDB AUTO_INCREMENT=4006 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
