/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;
/*!40101 SET SQL_MODE='NO_AUTO_VALUE_ON_ZERO,ONLY_FULL_GROUP_BY,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'*/;
/*!40103 SET TIME_ZONE='+00:00' */;
INSERT INTO `services` VALUES(1,161,"mbri-mobirise","But I must explain to you how all this mistaken","idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful.","1","2024-08-13 10:24:21","2024-08-16 17:09:40")
,(2,161,"mbri-hearth","Lorem ipsum dolor sit amet","quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum","1","2024-08-16 17:08:34","2024-08-16 17:08:34")
,(3,161,"mbri-info","On the other hand","we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain.","1","2024-08-16 17:11:31","2024-08-16 17:11:31")
,(4,161,"mbri-question","scelerisque ligula in, lacinia lectus. Vivamus ullamcorper","Curabitur vel ex laoreet, scelerisque ligula in, lacinia lectus. Vivamus ullamcorper, metus non accumsan suscipit, turpis neque vestibulum leo, euismod imperdiet nisi arcu quis ipsum. Integer sodales odio diam, ut elementum enim eleifend at.","1","2024-08-16 17:12:42","2024-08-16 17:13:13")
,(5,161,"Duis ea autem iste d","home-page","admin/home-page","1","2024-10-27 15:23:12","2024-10-27 15:23:12")
,(6,3975,"mbri-mobirise","Telemedicine & Remote Consultations","Dr. Schenker Jean-Martin offers telemedicine services to provide convenient and efficient healthcare from the comfort of your home. With secure video consultations, you can discuss your health concerns, receive medical advice, and follow up on treatment plans without needing to visit the clinic. This service is perfect for patients seeking flexible and immediate care","1","2024-11-05 12:38:15","2024-11-05 13:09:25")
,(7,3975,"mbri-hearth","Onsite Clinic Consultations","Experience comprehensive care at Dr. Schenker Jean-Martin’s clinic. Onsite consultations ensure you receive thorough assessments, in-person examinations, and immediate medical attention. The clinic is equipped to handle a variety of medical needs, from routine check-ups to more detailed diagnoses.\r\n\r\nKey features include:\r\n\r\nPersonal, face-to-face interaction\r\nAccess to in-depth medical evaluations and tests\r\nA welcoming environment for discussing your health concerns\r\nVisit the clinic for reliable and personalized healthcare. Book your appointment and receive expert care tailored to your needs.","1","2024-11-05 12:39:31","2024-11-05 13:08:45")
,(8,3975,"mbri-info","Health Screening and Preventative Care","Stay ahead of potential health issues with our comprehensive health screening and preventative care services. Dr. Schenker Jean-Martin emphasizes the importance of regular check-ups to monitor your health, identify risks early, and maintain overall wellness. Our tailored screening programs include blood tests, physical examinations, and personalized health assessments to ensure you and your family are on the path to a healthier life.","1","2024-11-05 13:07:13","2024-11-05 13:09:49")
;
