/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;
/*!40101 SET SQL_MODE='NO_AUTO_VALUE_ON_ZERO,ONLY_FULL_GROUP_BY,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'*/;
/*!40103 SET TIME_ZONE='+00:00' */;
INSERT INTO `diseases` VALUES(2,"General care medicine","1",NULL,NULL)
,(3,"COVID-19 vaccination","1",NULL,NULL)
,(4,"OB-GYN (obstetrician-gynecologist)","1",NULL,NULL)
,(5,"COVID-19 testing","1",NULL,NULL)
,(6,"Abdominal ultrasound","1",NULL,NULL)
,(7,"Adult remote emergency consultation","1",NULL,NULL)
,(8,"Aesthetic medicine","1",NULL,NULL)
,(9,"Allergic rhinitis","1",NULL,NULL)
,(10,"Angiology","1",NULL,NULL)
,(11,"Anual check up","1",NULL,NULL)
,(12,"Asthma","1",NULL,NULL)
,(13,"Blood sample","1",NULL,NULL)
,(14,"Blood test for check up","1",NULL,NULL)
,(15,"Botox","1",NULL,NULL)
,(16,"Botulinum toxin injection","1",NULL,NULL)
,(17,"Burnout","1",NULL,NULL)
,(18,"Children routine check-up","1",NULL,NULL)
,(19,"Dermatology and venereology","1",NULL,NULL)
,(20,"Diabetes screening","1",NULL,NULL)
,(21,"Does not accept new patients","1",NULL,NULL)
,(22,"Emergency","1",NULL,NULL)
,(23,"Emergency medicine","1",NULL,NULL)
,(24,"Flu vaccination","1",NULL,NULL)
,(25,"HPV / Humane papillomavirus vaccination","1",NULL,NULL)
,(26,"Hay fever","1",NULL,NULL)
,(27,"Hematology","1",NULL,NULL)
,(28,"Hyaluronic acid injection","1",NULL,NULL)
,(29,"Medical traffic examination LEVEL 1","1",NULL,NULL)
,(30,"Medical traffic examination LEVEL 2","1",NULL,NULL)
,(31,"Memory assessment","1",NULL,NULL)
,(32,"Mesotherapy","1",NULL,NULL)
,(33,"Osteoporosis screening","1",NULL,NULL)
,(34,"Pediatric remote emergency consultation","1",NULL,NULL)
,(35,"Radiofrequency","1",NULL,NULL)
,(36,"Radiography","1",NULL,NULL)
,(37,"Rheumatology","1",NULL,NULL)
,(38,"Sexology","1",NULL,NULL)
,(39,"Smoking cessation","1",NULL,NULL)
,(40,"Specialist in general internal medicine","1",NULL,NULL)
,(41,"Sports medicine","1",NULL,NULL)
,(42,"Tick-borne encephalitis vaccination (TBE)","1",NULL,NULL)
,(43,"Traumatology","1",NULL,NULL)
,(44,"Travel advice","1",NULL,NULL)
,(45,"Urinary tract infection (UTI)","1",NULL,NULL)
,(46,"Vaccination advice","1",NULL,NULL)
,(47,"Vaccination booklet update","1",NULL,NULL)
,(48,"X-ray","1",NULL,NULL)
,(49,"preventive medical checkup","1",NULL,NULL)
;
