# Generated by Django 5.1.7 on 2025-03-28 22:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(default='user', max_length=255)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.DateField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.BigIntegerField(blank=True, null=True)),
                ('city', models.BigIntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('Speaking_Languages', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('house_number', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('hin_email', models.CharField(blank=True, max_length=255, null=True)),
                ('fax_phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('fax_number', models.CharField(blank=True, max_length=255, null=True)),
                ('web_url', models.CharField(blank=True, max_length=255, null=True)),
                ('speciality', models.CharField(blank=True, max_length=255, null=True)),
                ('specialties', models.BigIntegerField(blank=True, null=True)),
                ('experties', models.CharField(blank=True, db_column='sxpertise', max_length=255, null=True)),
                ('service_type', models.CharField(choices=[('onsite', 'On-site'), ('remote', 'Remote'), ('both', 'Both')], default='onsite', max_length=10)),
                ('fees', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=255, null=True)),
                ('Access_info', models.CharField(blank=True, max_length=255, null=True)),
                ('healthcare_professional_info', models.TextField(blank=True, null=True)),
                ('about_me', models.TextField(blank=True, null=True)),
                ('profile_pic', models.CharField(blank=True, max_length=255, null=True)),
                ('otp', models.CharField(blank=True, max_length=255, null=True)),
                ('is_online', models.CharField(default='1', max_length=255)),
                ('is_active', models.CharField(default='0', max_length=255)),
                ('token', models.CharField(default='0', max_length=255)),
                ('status', models.CharField(default='0', max_length=255)),
                ('referral_code', models.CharField(blank=True, max_length=255, null=True)),
                ('institute_id', models.BigIntegerField(blank=True, null=True)),
                ('zefix_ide', models.CharField(blank=True, max_length=255, null=True)),
                ('extension_code', models.BigIntegerField(blank=True, null=True)),
                ('wallet', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sms_reminder', models.BooleanField(null=True)),
                ('sms_confirmation', models.BooleanField(null=True)),
                ('reviews', models.CharField(blank=True, db_column='reviwes', max_length=255, null=True)),
                ('patient_status', models.CharField(blank=True, max_length=255, null=True)),
                ('is_boosted', models.BooleanField(default=False)),
                ('boost_end_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
    ]
