# Generated by Django 5.1.7 on 2025-04-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_canton_country_expertise_language_specialties_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialties',
            name='embedding_vector',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
