# Generated by Django 5.1.7 on 2025-04-15 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_specialties_embedding_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialties',
            name='embedding_vector',
        ),
    ]
